options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: python:3.11
  entrypoint: bash
  args:
    - -c
    - |
      pip install \
        google-cloud-aiplatform \
        google-cloud-secret-manager \
        google-api-python-client \
        google-auth-oauthlib \
        google-auth

      python main.py
